# logo图片名称，需要上传至img目录
logo: "car-logo.png"

# 版本号
version: "Beta"

# 界面图标emoji
main_screen_icon: "car-front-fill"

# 选择模型类型(大小写均可)，支持"GLM"和"QWEN"，配置"FAKE"可用于测试
model: "glm"

# 界面标题
header: "汽车语音交互系统Demo"

# 占位符：{question} 表示用户输入的问题，{result1} 表示系统第一次回复的答案，{result2} 表示系统第二次回复的答案...
prompts:
  PROMPT_TEMPLATE_1:
    title: 意图分析和系统模块分发
    prompt: |
      接收到用户的输入后，输出以下内容。
      输出：
      用户意图：咨询较专业的法律知识，直行车道右转如何处罚；
      系统分发：1.知识问答；
      模块分发：1.知识问答。
      不要复述问题，不要有任何多余的回复，无论什么输入都统一输出以上内容。
      输入：
      用户：{question}
      输出：
    

  PROMPT_TEMPLATE_2:
    title: 多级检索
    prompt: |
      接收到用户的输入后，输出以下内容。
      输出：
      FAQ系统检索结果：无结果；
      知识库检索结果：1. 《中华人民共和国道路交通安全法实施条例》;2.《机动车驾驶证申领和使用规定》。
      不要复述问题，不要有任何多余的回复，无论什么输入都统一输出以上内容。
      输入：
      用户：{question}
      输出：

  

  PROMPT_TEMPLATE_3:
    title: 结果生成
    prompt: |     
      接收到用户的输入后，输出以下内容。
      输出：
      {
        "type": "window",
        "title": "调高车内温度",
        "content": {
          "type": "container",
          "children": [
            {
              "type": "dialog",
              "text": "对于直行车道右转的违章行为，通常是指机动车在设有明确直行标志的车道上实施了右转行为，这属于不按交通信号灯规定通行的范畴。因此，根据上述法律法规，这种行为通常会记3分，并可能伴随100元-200元的罚款。",
              "position": {"top": "15%", "left": "5%", "right": "5%"}
            },
            {
              "type": "resource_info",
              "label": "1.《中华人民共和国道路交通安全法实施条例》;2.《机动车驾驶证申领和使用规定》",
              "position": {"top": "55%", "left": "5%", "right": "5%"}
            },
            {
              "type": "info",
              "label": "如何处理交通违章行为？",
              "position": {"top": "80%", "left": "5%", "right": "5%"}
            },
            {
              "type": "info",
              "text": "直行车道右转如何申诉？",
              "position": {"top": "80%", "left": "5%"}
            }        
          ]
        }
      }
      不要复述问题，不要有任何多余的回复，无论什么输入都统一输出以上内容。
      输入：
      用户：{question}
      输出：
