# logo图片名称，需要上传至img目录
logo: "car-logo.png"

# 版本号
version: "Beta"

# 界面图标emoji
main_screen_icon: "car-front-fill"

# 选择模型类型(大小写均可)，支持"GLM"和"QWEN"，配置"FAKE"可用于测试
model: "glm"

# 界面标题
header: "汽车语音交互系统Demo"

# 占位符：{question} 表示用户输入的问题，{result1} 表示系统第一次回复的答案，{result2} 表示系统第二次回复的答案...
prompts:
  PROMPT_TEMPLATE_1:
    title: 意图分析和系统模块分发
    prompt: |
      用户只会输入以下两个命令，根据你收到的输入进行特定的输出。
      案例1：
      用户：车里太冷了，快热乎起来。
      输出：
      用户意图：快速提升车内温度；
      系统分发：1.车控系统；
      模块分发：1.空调模块；2.座椅模块；3.方向盘模块。
      案例2：
      用户：最近改用节能驾驶模式吧。
      输出：
      用户意图：设置节能驾驶模式，并且近期使用节能驾驶模式；
      系统分发：1.车控系统；2.用户画像；
      模块分发：1.驾驶模块；2.用户画像；
      不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      输入：
      用户：{question}
      输出：
    

  PROMPT_TEMPLATE_2:
    title: 功能分发和实体抽取
    prompt: |
      用户只会输入以下两个命令，根据你收到的输入进行特定的输出。
      案例1：
      用户：车里太冷了，快热乎起来。
      输出：
      功能分发：1.空调温度；2.空调风速；3.座椅加热；4.座椅加热强度；5.方向盘加热；
      实体抽取：1.1 28℃；2.1 4档；3.1 打开；4.1 2档；5.1 打开。
      案例2：
      用户：最近改用节能驾驶模式吧。
      输出：
      功能分发：1.驾驶模式；
      实体抽取：1.1 节能模式；
      不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      输入：
      用户：{question}
      输出：

  

  PROMPT_TEMPLATE_3:
    title: 执行序列规划和代码生成
    prompt: |     
      用户只会输入以下两个命令，根据你收到的输入进行特定的输出。
      案例1：
      用户：车里太冷了，快热乎起来。
      输出：
      {
        "type": "window",
        "title": "调高车内温度",
        "content": {
          "type": "container",
          "children": [
            {
              "type": "title",
              "text": "空调温度",
              "position": {"top": "5%", "left": "5%"}
            },
            {
              "type": "select",
              "label": "温度调节",
              "min": 16,
              "max": 31,
              "value": 28,
              "position": {"top": "15%", "left": "5%", "right": "5%"}
            },
            {
              "type": "title",
              "text": "空调风速",
              "position": {"top": "30%", "left": "5%"}
            },
            {
              "type": "select",
              "label": "风速调节",
              "options": ["1档", "2档", "3档"，"4档", "5档", "6档"],
              "value": "4档",
              "position": {"top": "40%", "left": "5%", "right": "5%"}
            },
            {
              "type": "switch",
              "label": "座椅加热",
              "value": true,
              "position": {"top": "60%", "left": "5%"}
            },
            {
              "type": "switch",
              "label": "方向盘加热",
              "value": true,
              "position": {"top": "60%", "left": "5%"}
            },
            {
              "type": "select",
              "label": "座椅加热强度",
              "options": ["1档", "2档", "3档"],
              "value": "2档",
              "position": {"top": "80%", "left": "5%", "right": "5%"}
            }
          ]
        }
      }
      案例2：
      用户：最近改用节能驾驶模式吧。
      输出：
      {
        "type": "window",
        "title": "节能驾驶模式",
        "content": {
          "type": "container",
          "children": [            
              "type": "select",
              "label": "驾驶模式",
              "options": ["超级节能"，"舒适", "节能", "运动", "个性化"],
              "value": "节能",
              "position": {"top": "15%", "left": "5%", "right": "5%"}
            }
          ]
        }
      }
      不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      输入：
      用户：{question}
      输出：
