# logo图片名称，需要上传至img目录
logo: "car-logo.png"

# 版本号
version: "Beta"

# 界面图标emoji
main_screen_icon: "car-front-fill"

# 选择模型类型(大小写均可)，支持"GLM"和"QWEN"，配置"FAKE"可用于测试
model: "glm"

# 界面标题
header: "汽车语音交互系统Demo"

# 占位符：{question} 表示用户输入的问题，{result1} 表示系统第一次回复的答案，{result2} 表示系统第二次回复的答案...
prompts:
  PROMPT_TEMPLATE_1:
    title: 意图分析和系统模块分发
    prompt: |
      根据用户输入进行指定回复。
      1、车里太冷了，快热乎起来。
      回复1;
      2、直行车道右转了扣几分？
      回复2；
    不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      如果用户的意图无法识别，请对用户进行提问以获取更多信息。
      输入：
      用户：{question}
      输出：

  PROMPT_TEMPLATE_2:
    title: 功能分发和实体抽取
    prompt: |
       根据用户输入进行指定回复。
      1、车里太冷了，快热乎起来。
      回复12;
      2、直行车道右转了扣几分？
      回复22；      
  不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      如果用户的意图无法识别，请对用户进行提问以获取更多信息。
      输入：
      用户：{question}
      输出：

  PROMPT_TEMPLATE_3:
    title: 执行序列规划和代码生成
    prompt: |
      根据用户输入进行指定回复。
      1、车里太冷了，快热乎起来。
      回复123;
      2、直行车道右转了扣几分？
      回复223；      
不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      如果用户的意图无法识别，请对用户进行提问以获取更多信息。
      输入：
      用户：{question}
      输出：
