# logo图片名称，需要上传至img目录
logo: "car-logo.png"

# 版本号
version: "Beta"

# 界面图标emoji
main_screen_icon: "car-front-fill"

# 选择模型类型(大小写均可)，支持"GLM"和"QWEN"，配置"FAKE"可用于测试
model: "glm"

# 界面标题
header: "汽车语音交互系统Demo"

# 占位符：{question} 表示用户输入的问题，{result1} 表示系统第一次回复的答案，{result2} 表示系统第二次回复的答案...
prompts:
  PROMPT_TEMPLATE_1:
    title: 意图分析和系统模块分发
    prompt: |
      根据用户的输入，完成指定的标准输出。
      案例1：
      用户：车里太冷了，快热乎起来。
      输出：111；
      案例2：
      用户：直行车道右转扣几分。
      输出：222；
      不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      如果用户的意图无法识别，请对用户进行提问以获取更多信息。
      输入：
      用户：{question}
      输出：
    

  PROMPT_TEMPLATE_2:
    title: 功能分发和实体抽取
    prompt: |
      根据用户的输入，完成指定的标准输出。
      案例1：
      用户：车里太冷了，快热乎起来。
      输出：11；
      案例2：
      用户：直行车道右转扣几分。
      输出：22；
      不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      下列意图仅供参考，如果用户的意图识别错误或无法匹配到系统，请对用户进行提问以获取更多信息。
      输入：
      用户：{question}
      输出：

  

  PROMPT_TEMPLATE_3:
    title: 执行序列规划和代码生成
    prompt: |     
      根据用户的输入，完成指定的标准输出。
      案例1：
      用户：车里太冷了，快热乎起来。
      输出：1；
      案例2：
      用户：直行车道右转扣几分。
      输出：2；
      不要复述问题，不要有任何多余的回复，严格按照格式要求开始回答。
      如果用户的意图无法匹配到模块，请对用户进行提问以获取更多信息。
      输入：
      用户：{question}
      输出：
